const FETCH_BOOKS_REQUEST = 'FETCH_BOOKS_REQUEST';
const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';
const FETCH_BOOK_REQUEST = 'FETCH_BOOK_REQUEST';
const FETCH_BOOK_SUCCESS = 'FETCH_BOOK_SUCCESS';
const FETCH_BOOK_FAILURE = 'FETCH_BOOK_FAILURE';
const SEARCH_BOOKS = 'SEARCH_BOOKS';
const FILTER_BOOKS = 'FILTER_BOOKS';
const BOOK_ADDED_TO_CART = 'BOOK_ADDED_TO_CART';
const PURCHASE_REQUEST = 'PURCHASE_REQUEST';
const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
const PURCHASE_FAILURE = 'PURCHASE_FAILURE';
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';

export {
  FETCH_BOOKS_REQUEST,
  FETCH_BOOKS_SUCCESS,
  FETCH_BOOKS_FAILURE,
  FETCH_BOOK_REQUEST,
  FETCH_BOOK_SUCCESS,
  FETCH_BOOK_FAILURE,
  SEARCH_BOOKS,
  FILTER_BOOKS,
  BOOK_ADDED_TO_CART,
  PURCHASE_REQUEST,
  PURCHASE_SUCCESS,
  PURCHASE_FAILURE,
  SIGN_IN,
  SIGN_OUT
}
